language: node_js  #设置语言

node_js: stable  #设置相应的版本

install:
  - npm install  #安装hexo及插件

script:
  - hexo cl  #清除
  - hexo g  #生成
  - hexo d  #生成 

after_script:

branches:
  only:
    - source  #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置
                    
env:
  global:
    - GH_REF: github.com/thinklife/thinklife.github.io.git  #设置GH_REF，注意更改yourname
