language: node_js
node_js: stable
install:
  - npm install
script:
  - hexo cl
  - hexo g

after_script: 

branches:
  only:
    - source
env:
  global:
    - GH_REF: github.com/thinklife/thinklife.github.io.git
before_install:
  - openssl aes-256-cbc -K $encrypted_230bb39e4a1b_key -iv $encrypted_230bb39e4a1b_iv -in CI_TOKEN.enc -out CI_TOKEN -d
