language: node_js
node_js: stable
install:
- npm install
script:
- hexo cl
- hexo g
- hexo d
after_script:
branches:
  only:
  - source
#env:
#  global:
#  - GH_REF: github.com/thinklife/thinklife.github.io.git
before_install:
- openssl aes-256-cbc -K $encrypted_230bb39e4a1b_key -iv $encrypted_230bb39e4a1b_iv
  -in .travis/travis.enc -out ~/.ssh/travis -d
- chmod 600 ~/.ssh/travis
- eval $(ssh-agent)
- ssh-add ~/.ssh/travis
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "HackHook"
- git config --global user.email "55269778@qq.com"
