language: node_js
node_js:
  - "9"

cache:
  directories:
    - node_modules

#env:
#  global:
#  - GH_REF: github.com/thinklife/thinklife.github.io.git
before_install:
  - openssl aes-256-cbc -K $encrypted_a0a084cfe161_key -iv $encrypted_a0a084cfe161_iv -in .travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - git config --global user.name "hackdapp"
  - git config --global user.email "hackdapp@gmail.com"
  - git submodule init
  - git submodule update

install:
  - npm install

script:
  - hexo cl
  - hexo g
  - hexo d

after_script:
  branches:
    only:
      - source
